import type { Pivot } from '../pivot.ts';

export interface EmittedFile {
  /** Repository-relative path. */
  path: string;
  contents: string;
  mode?: number;
  /**
   * `full`     — the build owns the whole file.
   * `frontmatter` — the build owns only the listed frontmatter keys of a source file.
   * `region`   — the build owns text between BEGIN/END markers inside a hand-written file.
   */
  kind?: 'full' | 'frontmatter' | 'region';
  /** For kind === 'frontmatter': the keys the build is allowed to rewrite. */
  keys?: string[];
  /** For kind === 'region': the marker name. */
  region?: string;
}

export interface Emitter {
  id: string;
  label: string;
  emit(p: Pivot): EmittedFile[];
}

export const MARKER = '@generated by scripts/build.ts from content/ — DO NOT EDIT';

export function mdHeader(): string {
  return `<!-- ${MARKER} -->\n`;
}

export function hashHeader(): string {
  return `# ${MARKER}\n`;
}

/** Fail the build rather than silently shipping a rule file the harness will truncate. */
export function assertUnder(file: EmittedFile, limit: number, what: string): void {
  if (file.contents.length > limit) {
    throw new Error(
      `${file.path}: ${file.contents.length} characters exceeds the ${what} budget of ${limit}. ` +
        `Shorten the index or split the tag group.`,
    );
  }
}
